[package]
name = "gom-server"
version = "0.1.0"
authors = ["0x130C <0x130c@gmail.com>"]

[dependencies]
actix = "0.7.4"
actix-web = "0.7.8"
env_logger = "0.5.13"
serde = "1.0.79"
serde_json = "1.0.32"
serde_derive = "1.0.79"
futures = "0.1.24"
